name = "BayesianInference"
uuid = "a1b2c3d4-e5f6-7890-1234-567890abcdef"
version = "0.1.0"

[deps]
CondaPkg = "992eb4ea-22a4-4c89-a5bb-47a3300528ab"
PythonCall = "6099a3de-0909-46bc-b1f4-468b9a2dfc0d"

[compat]
julia = "1.12"
CondaPkg = "0.2"
PythonCall = "0.9"
