name = "BayesianInference"
uuid = "d122d8d1-e425-46db-8770-26312790ade9"
version = "0.1.0"

[deps]
CondaPkg = "992eb4ea-22a4-4c89-a5bb-47a3300528ab"
PythonCall = "6099a3de-0909-46bc-b1f4-468b9a2dfc0d"

[compat]
julia = "1.2"
CondaPkg = "0.2"
PythonCall = "0.9.30"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]


